services:
  db:
    container_name: public-sector-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: ps
      PGDATA: /data/postgres
    volumes:
      - ./data/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  pgadmin:
    container_name: public-sector-pgadmin
    image: dpage/pgadmin4:8.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin-service:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    
  redis:
    container_name: public-sector-redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]

volumes:
  data-pgadmin-service: