services:

  db:
    container_name: public-sector-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: ps
      POSTGRES_PASSWORD: ps
      PGDATA: /data/postgres
    volumes:
      - ./data/:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ps -d ps" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  
  pgadmin:
    container_name: public-sector-pgadmin
    image: dpage/pgadmin4:8.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - data-pgadmin-service:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
  
  redis:
    container_name: public-sector-redis
    image: redis:7.4.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]
  
  redis-insight:
    container_name: public-sector-redisinsight
    image: redis/redisinsight:2.66
    environment:
      - REDISINSIGHT_PASSWORD=ps
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: unless-stopped
  
  app:
    container_name: public-sector-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ps;Username=ps;Password=ps
      - Redis__Host=redis
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    restart: unless-stopped


volumes:
  data-pgadmin-service: