// <auto-generated />
using System;
using Infrastructure.Persistence.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250207123618_AddOrganisationEntity")]
    partial class AddOrganisationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Definition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_definitions");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_definitions_parent_id");

                    b.ToTable("definitions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int?>("AtmCount")
                        .HasColumnType("integer")
                        .HasColumnName("atm_count");

                    b.Property<int?>("BranchCount")
                        .HasColumnType("integer")
                        .HasColumnName("branch_count");

                    b.Property<byte?>("CenterClass")
                        .HasColumnType("smallint")
                        .HasColumnName("center_class");

                    b.Property<Guid?>("ConvertedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_from_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DistributionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("distribution_status");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<int?>("DocumentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid?>("GeographicRegionDefId")
                        .HasColumnType("uuid")
                        .HasColumnName("geographic_region_def_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Latitude")
                        .HasColumnType("text")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocalStatus")
                        .HasColumnType("integer")
                        .HasColumnName("local_status");

                    b.Property<string>("Longitude")
                        .HasColumnType("text")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("OrganisationType")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("ProcedureRegionDefId")
                        .HasColumnType("uuid")
                        .HasColumnName("procedure_region_def_id");

                    b.Property<int?>("WagePayMachine")
                        .HasColumnType("integer")
                        .HasColumnName("wage_pay_machine");

                    b.Property<int?>("WageTakeMachine")
                        .HasColumnType("integer")
                        .HasColumnName("wage_take_machine");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("ConvertedFromId")
                        .HasDatabaseName("ix_organisations_converted_from_id");

                    b.HasIndex("GeographicRegionDefId")
                        .HasDatabaseName("ix_organisations_geographic_region_def_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organisations_parent_id");

                    b.HasIndex("ProcedureRegionDefId")
                        .HasDatabaseName("ix_organisations_procedure_region_def_id");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrganisationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_organisation_logs");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_organisation_logs_organisation_id");

                    b.ToTable("organisation_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Definition", b =>
                {
                    b.HasOne("Domain.Entities.Definition", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_definitions_definitions_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Organisation", b =>
                {
                    b.HasOne("Domain.Entities.Organisation", "ConvertedFrom")
                        .WithMany()
                        .HasForeignKey("ConvertedFromId")
                        .HasConstraintName("fk_organisations_organisations_converted_from_id");

                    b.HasOne("Domain.Entities.Definition", "GeographicRegionDef")
                        .WithMany()
                        .HasForeignKey("GeographicRegionDefId")
                        .HasConstraintName("fk_organisations_definitions_geographic_region_def_id");

                    b.HasOne("Domain.Entities.Organisation", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_organisations_organisations_parent_id");

                    b.HasOne("Domain.Entities.Definition", "ProcedureRegionDef")
                        .WithMany()
                        .HasForeignKey("ProcedureRegionDefId")
                        .HasConstraintName("fk_organisations_definitions_procedure_region_def_id");

                    b.Navigation("ConvertedFrom");

                    b.Navigation("GeographicRegionDef");

                    b.Navigation("Parent");

                    b.Navigation("ProcedureRegionDef");
                });

            modelBuilder.Entity("Domain.Entities.OrganisationLog", b =>
                {
                    b.HasOne("Domain.Entities.Organisation", "Organisation")
                        .WithMany("OrganisationLogs")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_logs_organisations_organisation_id");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Domain.Entities.Organisation", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("OrganisationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
